name: Publish Docker image
on:
  release:
    types: [created]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build the tagged Docker image
        run: docker build --rm --no-cache -t kalra20/app:${GITHUB_REF##*/} -t kalra20/app:latest .
      - name: Push the tagged Docker image
        run: docker push kalra20/app:${GITHUB_REF##*/}
      - name: Push the latest Docker image
        run: docker push kalra20/app:latest
